#ifndef NOMINMAX
#define NOMINMAX
#endif
#pragma once
#ifndef IMGUI_DEFINE_MATH_OPERATORS
#define IMGUI_DEFINE_MATH_OPERATORS
#endif
#include <Windows.h>
#include <d3d11.h>
#include <algorithm>
#include <array>
#include <codecvt>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <functional>
#include <locale>
#include <map>
#include <memory>
#include <optional>
#include <sstream>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>
#include "../../front/back/misc/imgui/backends/imgui.h"
#include "../../front/back/misc/imgui/backends/imgui_internal.h"
#include "compatibility.hh"
#include "animations/animations.hh"
#include "render/render.hh"
#include "framework/context/context.hh"
#include "framework/gui/base_element/base_element.hh"
#include "framework/gui/button/button.hh"
#include "framework/gui/checkbox/checkbox.hh"
#include "framework/gui/colorpicker/colorpicker.hh"
#include "framework/gui/dropdown/dropdown.hh"
#include "framework/gui/keybind/keybind.hh"
#include "framework/gui/listbox/listbox.hh"
#include "framework/gui/multibox/multibox.hh"
#include "framework/gui/slider/slider.hh"
#include "framework/gui/textinput/textinput.hh"
#include "framework/gui/popup/popup.hh"
#include "framework/gui/search/search.hh"
#include "framework/gui/tab/tab.hh"
#include "framework/gui/interactive_preview/interactive_preview.hh"
#include "framework/gui/child/child.hh"
#include "framework/gui/window/window.hh"
